paths:
  /user-management/user:
    get:
      tags:
        - user-managment
      description: Get all users
      summary: Get all users
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        user_key:
                          type: string
                          format: uuid
                        name: 
                          type: string
                        age:
                          type: integer
                        DOB: 
                          type: string
                          format: date
                        email: 
                          type: string
                          format: email
                        password: 
                          type: string
  /user-management/signup:
    post:
      tags:
        - user-managment
      description: create a new user
      summary: create a new user
      responses:
        200:
          description: user was created successfully!!!
          content:
            application/json:
              schema:
                type: object
                properties:
                  key:
                    type: string
                    format: uuid
      requestBody:
        description: enter the data of the user to create it
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                age:
                  type: integer
                email:
                  type: string
                  format: email
                DOB: 
                  type: string
                  format: date
                password: 
                  type: string
                  format: password
        required: true




          

