components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /assign/permission:
    post:
      tags:
        - privilege-management
      description: assign permission
      requestBody: 
        descrition:  assign permission
        content:
          application/json:
            schema:
              type: object
              required:
                - resource
                - operation
              properties:
                resource:
                  type: string
                operation:
                  type: string
                  enum: 
                    - create
                    - read
                    - update
                    - delete
      responses: 
        201:
          description: permission created!!!
          content: 
            application/json:
              schema:
                type: object
                properties:
                  permission:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
  /assign/permission_to_role:
    post:
      tags:
        - privilege-management
      description: assign permission to role
      requestBody: 
        descrition: assign permission to role
        content:
          application/json:
            schema:
              type: object
              required:
                - role_name
                - permission_name
              properties:
                role_name:
                  type: string
                permission_name:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: assign permission to role successfully!!!
  /assign/role_to_user:
    post: 
      tags:
        - privilege-management
      description: assign role to user
      requestBody:
        descrition: assign role to user
        content:
          application/json:
            schema:
              type: object
              required:
               - role_name    
               - user_id
              properties:        
                role_name:
                  type: string
                user_id:
                  type: array
                  items:
                    type: string
      responses:
        201:
          description: assigned role to user successfully!!!
  /unassign/role_from_user:
      delete: 
        tags:
          - privilege-management
        description: unassign role from user
        requestBody:
          descrition: unassign role from user
          content:
            application/json:
              schema:
                type: object
                required:
                - role   
                - userId
                properties:        
                  role:
                    type: string
                  userId:
                    type: string
        responses:
          200:
            description: unassign role from user successfully!!!
  /unassign/permission_from_role:
      delete: 
        tags:
          - privilege-management
        description: unassign permission from role
        requestBody:
          descrition: unassign permission from role
          content:
            application/json:
              schema:
                type: object
                required:
                - role   
                - permission
                properties:        
                  role:
                    type: string
                  permission:
                    type: array
                    items:
                      type: string
        responses:
          200:
            description: unassign permission from role successfully!!!
  /permission:
      delete: 
        tags:
          - privilege-management
        description: delete permission
        requestBody:
          descrition: delete permission
          content:
            application/json:
              schema:
                type: object
                required:  
                - permission
                properties:        
                  permission:
                    type: array
                    items:
                      type: string
        responses:
          200:
            description: delete permission successfully!!!
                        

              

  